#!/bin/sh

set -xa
# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}

mkdir $DATA
cd $DATA 

###################################
# Run setpdy and initialize PDY variables
###################################
export cycle=${cycle:-t${cyc:?}z}
if [ $RUN_ENVIR = 'nco' ]
then
setpdy.sh
. ./PDY
fi

export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_AWIPS}

####################################
# Specify Execution Areas
####################################
if [ $MODEL = 'arw' ]
then
export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}
export PARMutil=${PARMutil:-$HOMEhiresw/parm/arw/wmo}
else
export HOMEfv3=${HOMEfv3:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXECfv3=${EXECfv3:-$HOMEfv3/exec/fv3}
export FIXfv3=${FIXfv3:-$HOMEfv3/fix/fv3}
export PARMfv3=${PARMfv3:-$HOMEfv3/parm/fv3}
export USHfv3=${USHfv3:-$HOMEfv3/ush/fv3}
export PARMutil=${PARMutil:-$HOMEfv3/parm/fv3/wmo}
fi

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

#####################################
# Define COM directories
#####################################
export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTwmo=${COMOUTwmo:-${COMOUT}/wmo}

mkdir -p $COMOUTwmo

export pgmout="OUTPUT.$$"

########################################################
# Run the ex-script
#
if [ $MODEL = 'arw' ] 
then
$HOMEhiresw/scripts/arw/exhiresw_awips.sh.ecf
else
$HOMEfv3/scripts/fv3/exhiresw_awips.sh.ecf
fi
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
