#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA 

# Run setpdy and initialize PDY variables
export cycle=${cycle:-t${cyc}z}
if [ $RUN_ENVIR = 'nco' ]
then
setpdy.sh
. ./PDY
fi

####################################
# Specify Execution Areas
####################################
if [ ${MODEL} = 'arw' ]
then
export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export GEMPAKhiresw=${GEMPAKhiresw:-$HOMEhiresw/gempak}
export fend=48
else
export HOMEfv3=${HOMEfv3:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export GEMPAKhiresw=${GEMPAKhiresw:-$HOMEfv3/gempak}
export fend=60
fi

export finc=1
export finc3=3

export fstart=00
export model=${NEST}${MODEL}

export GRIB=5km
export EXT=
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_GEMPAK}

#
# Copy model specific GEMPAK tables into working directory
#
cp $GEMPAKhiresw/fix/*.tbl .
err=$?

if [ $err -ne 0 ]
then
msg="FATAL ERROR:  Did not copy fix .tbl files needed for GEMPAK processing"
err_exit $msg
fi

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw} 
  
#####################################
# Define COM directories
#####################################
export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/hiresw.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/hiresw.${PDY}}

if [ ! -f $COMOUT/gempak ] ; then
  mkdir -p -m 775 $COMOUT/gempak
fi
 
export pgmout="OUTPUT.$$"

env

#################################################################
# Execute the script
if [ $MODEL = 'arw' ]
then
$HOMEhiresw/scripts/arw/exhiresw_gempak.sh.ecf
else
$HOMEfv3/scripts/fv3/exhiresw_gempak.sh.ecf
fi
#################################################################

cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
