#!/bin/ksh
set -xe

. $HOMEfv3/ush/fv3/run_commands_bc.sh

####################################
# Specify Execution Areas
####################################
export CHGRESEXEC=$EXECfv3/hireswfv3_chgres_cube

####################################
# Run setpdy and initialize PDY variables
####################################

if [ ${RUN_ENVIR} = 'prod' ]
then
setpdy.sh
. ./PDY

export CDATE=${PDY}${cyc}
fi

export month=`echo $CDATE | cut -c 5-6`
export day=`echo $CDATE | cut -c 7-8`

#####################################
# Working directories
#####################################

echo DATA is $DATA
echo DATAROOT is $DATAROOT

echo NEST is $NEST
echo MODEL is $MODEL
echo cyc is $cyc
echo envir is $envir


export DATA=${DATA:-${DATAROOT:?}/hiresw.makeic_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-/gpfs/dell1/nco/ops/com/gfs/prod}
export GBCOMINgfs=${GBCOMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export INIDIR=${COMINgfs}/gfs.$PDY/$cyc

export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

if [ $tmmark = tm00 ] ; then	# SAR without DA
  export INPdir=$NWGES/anl.${NEST}.$tmmark
fi
mkdir -p $INPdir

#####################################
# wcoss environment settings
#####################################
export CDUMP=gfs
export CDAS=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=1		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled

env

#####################################
# Generate the ICs and BC hour 0
#####################################
# Execute the script.
${HOMEfv3}/scripts/fv3/exhiresw_make_ic.sh.ecf
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
