#!/bin/sh

########################################
# RUNS HIRESW POST JOB
########################################
set -xa
export PS4='$SECONDS + ' 
date

if [ $MODEL = 'fv3' ]
then
. $HOMEfv3/ush/fv3/hiresw_run_commands_forecast.sh
fi

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

####################################
# SENDCOM - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
if [ $MODEL = 'fv3' ]
then
export POSTGPEXEC=${EXECfv3}/hireswfv3_post
# export WGRIB2=${WGRIB2:-${EXECfv3}/hireswfv3_wgrib2}
fi

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY and CDATE are passed in through Rocoto xml

if [ $RUN_ENVIR = 'prod' -o $MODEL = 'arw' ]
then
setpdy.sh
. ./PDY
fi

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/hiresw.post_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
export INPUT_DATA=${INPUT_DATA:-${DATAROOT:?}/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}
mkdir -p $DATA/${fhr}
cd $DATA/${fhr}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

if [ $MODEL = 'arw' ]
then
export IOBUF_PARAMS='*:size=64M:count=8:verbose'

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}

fi

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY and CDATE are passed in through Rocoto xml

if [ $RUN_ENVIR = 'prod' -o $MODEL = 'arw' ]
then
setpdy.sh
. ./PDY
fi

export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

################################################
# Copy Forecast files from com
################################################

if [ $MODEL = 'arw' ]
then
. $COMIN/hiresw.t${cyc}z.${NEST}${MODEL}.envir.sh
fi

export tmmark=tm00

########################################################
# Run the ex-script
#

if [ $MODEL = 'fv3' ]
then
${HOMEfv3}/scripts/fv3/exhiresw_post.sh.ecf
else
${HOMEhiresw}/scripts/arw/exhiresw_postg2.sh.ecf
fi

export err=$?

#
########################################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

date
