#!/bin/sh

########################################
# Set up environment for HIRESW FCST
########################################
set -xa
export PS4='$SECONDS + '
date

export MP_PULSE=0
unset MP_DEBUG_NOTIMEOUT #recommended by Farid to avoid time out message

#####################################
# Working directories
#####################################
export DATA=${DATA:-${DATAROOT:?}/hiresw.forecast_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
mkdir -p $DATA
cd $DATA

# Run setpdy and initialize PDY variables
export cycle=${cycle:-t${cyc}z}
if [ $RUN_ENVIR = 'nco' ]
then
setpdy.sh
. ./PDY
fi

export CDATE=${PDY}${cyc}
offset=`echo $tmmark | cut -c 3-4`
export CYCLEanl=`$NDATE -${offset} $CDATE`

export MP_LABELIO=YES
export MP_USE_BULK_XFER=yes

####################################
# Specify Execution Areas
####################################
if [ $MODEL = 'arw' ]
then
export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}
else
export HOMEfv3=${HOMEfv3:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXECfv3=${EXECfv3:-$HOMEfv3/exec/fv3}
export FIXfv3=${FIXfv3:-$HOMEfv3/fix/fv3}
export PARMfv3=${PARMfv3:-$HOMEfv3/parm/fv3}
export USHfv3=${USHfv3:-$HOMEfv3/ush/fv3}
export FIXsar=${FIXsar:-$HOMEfv3/fix/fv3/fix_sar/$NEST}
export FIXam=${FIXam:-$HOMEfv3/fix/fv3/fix_am}
export FIXco2=${FIXco2:-$FIXam/fix_co2_proj}
export CASE=C768
. $PARMfv3/run_commands_forecast.config
fi

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

#####################################
# Define COM directories
#####################################
export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

mkdir -p $COMOUT

export pgmout="OUTPUT.$$"
export pgmerr=errfile

#####################################
# wcoss environment settings
#####################################
if [ ${MODEL} = "arw" ]
then
  export MP_SHARED_MEMORY=yes
  export MP_USE_TOKEN_FLOW_CONTROL=yes
  export MP_INSTANCES=2
# else
#   export KMP_AFFINITY=scatter
#   export OMP_NUM_THREADS=2
#   export OMP_STACKSIZE=1024m
fi

env

#####################################
# Execute the script.

if [ ${MODEL} = "fv3" ]
then
${HOMEfv3}/scripts/fv3/exhiresw_forecast.sh.ecf
else
${HOMEhiresw}/scripts/arw/exhiresw_fcst.sh.ecf
fi
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

if [ $err -eq 0 ]
then
msg="JOB $job FOR NEST=${NEST}${MODEL} HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
fi

exit $err
