#!/bin/sh

########################################
# Set up environment for HIRESW FCST
########################################
set -xa
export PS4='$SECONDS + '
date

export MP_PULSE=0
unset MP_DEBUG_NOTIMEOUT #recommended by Farid to avoid time out message

if [ $MODEL = 'fv3' ]
then
. $HOMEfv3/ush/fv3/run_commands_forecast.sh
fi

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}


offset=`echo $tmmark | cut -c 3-4`
export CYCLEanl=`$NDATE -${offset} $CDATE`

#####################################
# Working directories
#####################################

export DATA=${DATA:-${DATAROOT:?}/hiresw.forecast_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
mkdir -p $DATA
cd $DATA

ecflow_client --event release_downstream

####################################
# Determine Job Output Name on System
####################################

export pid=$$
export outid="LL$job"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

export cycle=${cycle:-t${cyc}z}
export MP_LABELIO=YES
export MP_USE_BULK_XFER=yes

if [ $MODEL = 'arw' ]
then
export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}
fi

# Run setpdy and initialize PDY variables

if [ $MODEL = 'arw' -o $RUN_ENVIR = "prod" ]
then
setpdy.sh
. PDY
fi

export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

if [ ${MODEL} = "arw" ]
then
  export MP_SHARED_MEMORY=yes
  export MP_USE_TOKEN_FLOW_CONTROL=yes
  export MP_INSTANCES=2
fi



#####################################
# Define COM directories
#####################################



export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

#####################################
# wcoss environment settings
#####################################
if [ ${MODEL} = "arw" ]
then
  export MP_SHARED_MEMORY=yes
  export MP_USE_TOKEN_FLOW_CONTROL=yes
  export MP_INSTANCES=2
else
   export KMP_AFFINITY=scatter
   export OMP_NUM_THREADS=2
   export OMP_STACKSIZE=1024m
fi

# export SENDECF=NO


env

#####################################
# Execute the script.

if [ ${MODEL} = "fv3" ]
then
${HOMEfv3}/scripts/fv3/exhiresw_forecast.sh.ecf
else
${HOMEhiresw}/scripts/arw/exhiresw_fcst.sh.ecf
fi
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

if [ $err -eq 0 ]
then
msg="JOB $job FOR NEST=${NEST}${MODEL} HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
fi

exit $err
