#!/bin/ksh

set -xa
export PS4='$SECONDS + '

#####################################
# Working directories
#####################################

export DATA=${DATA:-${DATAROOT:?}/hiresw.makeic_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
mkdir -p $DATA
cd $DATA

echo DATA is $DATA
echo DATAROOT is $DATAROOT

echo NEST is $NEST
echo MODEL is $MODEL
echo cyc is $cyc
echo envir is $envir

####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${cyc}z}
if [ ${RUN_ENVIR} = 'nco' ]
then
setpdy.sh
. ./PDY

export CDATE=${PDY}${cyc}
fi

export month=`echo $CDATE | cut -c 5-6`
export day=`echo $CDATE | cut -c 7-8`

####################################
# Specify Execution Areas
####################################
export HOMEfv3=${HOMEfv3:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXECfv3=${EXECfv3:-$HOMEfv3/exec/fv3}
export FIXfv3=${FIXfv3:-$HOMEfv3/fix/fv3}
export PARMfv3=${PARMfv3:-$HOMEfv3/parm/fv3}
export USHfv3=${USHfv3:-$HOMEfv3/ush/fv3}
export CHGRESEXEC=$EXECfv3/hireswfv3_chgres_cube
export UTILush=${UTILush:-$HOMEfv3/util/ush}

export FIXsar=${FIXsar:-$HOMEfv3/fix/fv3/fix_sar/$NEST}
export FIXam=${FIXam:-$HOMEfv3/fix/fv3/fix_am}
export FIXco2=${FIXco2:-$FIXam/fix_co2_proj}
export CASE=C768

. $PARMfv3/run_commands_bc.config

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-$(compath.py gfs/prod)}
export GBCOMINgfs=${COMINgfs:-$(compath.py gfs/prod)}
export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)}
export INIDIR=${COMINgfs}/gfs.$PDY/$cyc

export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
mkdir -p $COMOUT

export pgmout="OUTPUT.$$"
export pgmerr=errfile

#####################################
# wcoss environment settings
#####################################
export CDUMP=gfs
export CDAS=gfs
export LEVS=65
export LSOIL=4
export REGIONAL=1		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled

env

#####################################
# Generate the ICs and BC hour 0
#####################################
# Execute the script.
${HOMEfv3}/scripts/fv3/exhiresw_make_ic.sh.ecf
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
