#!/bin/sh

########################################
# RUNS HIRESW POST JOB
########################################

set -xa
export PS4='$SECONDS + '

if [ $MODEL = 'fv3' ]
then
. $HOMEfv3/ush/fv3/hireswfv3_envir.sh
. $USHfv3/run_commands_forecast.sh
fi

export cycle=${cycle:-t${cyc}z}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

####################################
# SENDCOM - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
if [ $MODEL = 'fv3' ]
then
export POSTGPEXEC=${EXECfv3}/hireswfv3_post.x
export WGRIB2=${WGRIB2:-${EXECfv3}/wgrib2new}
fi

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY and CDATE are passed in through Rocoto xml

if [ $RUN_ENVIR = 'prod' -o $MODEL = 'arw' ]
then
setpdy.sh
. ./PDY
fi

#####################################
# Working directories
#####################################

export DATA=${DATA:-${DATAROOT:?}/hiresw.postodd_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
export INPUT_DATA=${INPUT_DATA:-${DATAROOT:?}/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}

if [ ! -e $DATA ]
then
mkdir -p $DATA
fi

cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

if [ $MODEL = 'arw' ]
then
export IOBUF_PARAMS='*:size=64M:count=8:verbose'

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}
fi

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`

#####################################
# Define COM directories
#####################################
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES
export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

if [ $MODEL = 'arw' ]
then
. $COMIN/hiresw.t${cyc}z.${NEST}${MODEL}.envir.sh
fi

export tmmark=tm00

#####################################
# wcoss environment settings
#####################################
export OMP_NUM_THREADS=1

env

#####################################
# Execute the script.
if [ $MODEL = 'fv3' ]
then
${HOMEfv3}/scripts/fv3/exhiresw_post_odd.sh
else
${HOMEhiresw}/scripts/arw/exhiresw_postg2_odd.sh.ecf
fi

export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

exit $err
