#!/bin/sh

set -x 
export PS4='$SECONDS + '
echo `date` $0 `date -u` begin

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA

cd $DATA


# Run setpdy and initialize PDY variables
export cycle=t${cyc}z
if [  $RUN_ENVIR = 'nco' ]
then
setpdy.sh
. ./PDY
fi

###############################
# Specify NET and RUN name
##############################
export NET=hiresw
export RUN=hiresw

export pgmout="OUTPUT.$$"

env

########################################################
# Start remove the directories
########################################################
cd $DATAROOT
for mod in fv3 arw
 do
  if [ $cyc -eq 00 -o $cyc -eq 12 ]; then
    for nest in hi guam conus himem2 conusmem2
    do
      for step in ungrib metgrid makebc makeic forecast post prdgen smartinit smartinitb bufrpost awips gempak
      do
        if [ -d hiresw.${step}_${nest}_${mod}_${cyc}_${envir} ]; then
         rm -rf hiresw.${step}_${nest}_${mod}_${cyc}_${envir}
        fi
        
      done
    done
  else
    for nest in pr ak prmem2 akmem2
    do
      for step in ungrib metgrid makebc makeic forecast post prdgen smartinit smartinitb bufrpost awips gempak
      do
        if [ -d hiresw.${step}_${nest}_${mod}_${cyc}_${envir} ]; then
         rm -rf hiresw.${step}_${nest}_${mod}_${cyc}_${envir}
        fi
      done
    done
  fi
done

offset=120
export DAYdel=`$NDATE -${offset} $PDY${cyc} | cut -c1-8`

echo DAYdel is $DAYdel
echo will delete /gpfs/hps2/ptmp/Matthew.Pyle/com/hiresw/para/hiresw.${DAYdel}
rm -rf /gpfs/hps2/ptmp/Matthew.Pyle/com/hiresw/para/hiresw.${DAYdel}

date
