#!/bin/sh 

########################################
# Preliminary data setup step
########################################
set -xa
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/hiresw.preprap_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}

# Remove old forecast data directory if it exists
if [ -d $DATA ]; then
   rm -rf $DATA
fi

mkdir -p $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDDBN=NO

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
#export GESINnam=${GESINnam:-${GESROOTp2:?}/prod/nam.${PDY}}
export GESINnam=${GESINnam:-${GESROOTp3:?}/prod/nam.${PDY}}
export COMINrap=${COMINrap:-${COMROOThps:?}/rap/prod/rap.${PDY}}
export COMINhur=${COMINhur:-$(compath.py hur/prod/inpdata)}

mkdir -p -m 775 $COMOUT
 
########################################################
# Execute the script.
${HOMEhiresw}/scripts/arw/exhiresw_prelim_rap.sh.ecf
########################################################

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
