#!/bin/sh

set -xa
# #### 07/30/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

if [ $MODEL = 'fv3' ]
then
. $HOMEfv3/ush/fv3/hireswfv3_envir.sh
fi


###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/hiresw.awips_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}

mkdir $DATA
cd $DATA 

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_AWIPS}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc:?}z}

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`

if [ $MODEL = 'arw' ]
then
export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}
export PARMutil=${PARMutil:-$HOMEhiresw/parm/arw/wmo}

else

export PARMutil=${PARMutil:-$HOMEfv3/parm/fv3/wmo}
fi


###################################
# Set up the UTILITIES
###################################
if [ $MODEL = 'arw' -o $RUN_ENVIR = 'prod' ]
then
setpdy.sh
. PDY
fi

export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

mkdir -p $COMOUT/wmo

export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}
 
########################################################
# Run the ex-script
#
if [ $MODEL = 'arw' ] 
then
$HOMEhiresw/scripts/arw/exhiresw_awips.sh.ecf
else
$HOMEfv3/scripts/fv3/exhiresw_awips.sh
fi
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
