#!/bin/sh

########################################
# Runs HIRESW WRFBUFR and SNDP programs
########################################
set -xa
export PS4='$SECONDS + '
date

#####################################
# Working directories
#####################################

export DATA=${DATA:-${DATAROOT:?}/hiresw.bufrpost_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
export INPUT_DATA=${INPUT_DATA:-${DATAROOT:?}/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}

mkdir -p $DATA
cd $DATA

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY and CDATE are passed in through Rocoto xml

if [ $RUN_ENVIR = 'nco' ]
then
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY
fi

####################################
# SENDCOM - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEobsproc_shared_bufr_cword=${HOMEobsproc_shared_bufr_cword:-${NWROOT:?}/obsproc_shared/bufr_cword.${obsproc_shared_bufr_cword_ver:?}}
export USHobsproc_shared_bufr_cword=${USHobsproc_shared_bufr_cword:-$HOMEobsproc_shared_bufr_cword/ush}
export EXECobsproc_shared_bufr_cword=${EXECobsproc_shared_bufr_cword:-$HOMEobsproc_shared_bufr_cword/exec}

if [ $MODEL = 'arw' ]
then
export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec/arw}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix/arw}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm/arw}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush/arw}
else
export HOMEfv3=${HOMEfv3:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXECfv3=${EXECfv3:-$HOMEfv3/exec/fv3}
export FIXfv3=${FIXfv3:-$HOMEfv3/fix/fv3}
export PARMfv3=${PARMfv3:-$HOMEfv3/parm/fv3}
export USHfv3=${USHfv3:-$HOMEfv3/ush/fv3}
export FIXsar=${FIXsar:-$HOMEfv3/fix/fv3/fix_sar/$NEST}
export POSTGPEXEC=${EXECfv3}/hireswfv3_bufr
. $PARMfv3/run_commands_forecast.config
fi

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

#####################################
# Define COM directories
#####################################
export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
mkdir -p $COMOUT

export pgmout="OUTPUT.$$"
export pgmerr=errfile

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_BUFR}
#####################################
# wcoss environment settings
#####################################
export OMP_NUM_THREADS=1

env

#####################################
# Execute the script.

if [ $MODEL = 'fv3' ]
then
${HOMEfv3}/scripts/fv3/exhiresw_bufr.sh.ecf
else
${HOMEhiresw}/scripts/arw/exhiresw_wrfbufr.sh.ecf
fi

export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
