#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

if [ $MODEL = 'fv3' ]
then
. $HOMEfv3/jobs/JHIRESW_ENVIR
fi


###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw} 
  
###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$

if [ $MODEL = 'fv3' ]
then
export DATA=${DATA:-${DATAROOT:?}/${job:?}}
else
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
fi

mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
if [ ${MODEL} = 'arw' ]
then
export GEMPAKhiresw=${GEMPAKhiresw:-$HOMEhiresw/gempak}
else
export GEMPAKhiresw=${GEMPAKhiresw:-$HOMEfv3/gempak}
fi

export finc=1
export fend=48

export fstart=00
export model=${NEST}${MODEL}

export GRIB=5km
export EXT=
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_GEMPAK}

#
# Copy model specific GEMPAK tables into working directory
#
cp $GEMPAKhiresw/fix/*.tbl .
err=$?

if [ $err -ne 0 ]
then
msg="FATAL ERROR:  Did not copy fix .tbl files needed for GEMPAK processing"
err_exit $msg
fi


# Run setpdy and initialize PDY variables
if [ $MODEL = 'arw' -o $RUN_ENVIR = 'prod' ]
then
setpdy.sh
. ./PDY
fi


export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/hiresw.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/nawips/${envir}/hiresw.${PDY}}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

#################################################################
# Execute the script
if [ $MODEL = 'arw' ]
then
$HOMEhiresw/scripts/arw/exnawips_hiresw.sh.ecf
else
$HOMEfv3/scripts/fv3/exhiresw_gempak.sh
fi
#################################################################

cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
