#!/bin/ksh
set -x

. $HOMEfv3/jobs/JHIRESW_ENVIR

##################################
# Run setpdy and initialize PDY variables
##################################
# PDY is passed in through Rocoto xml
#setpdy.sh
#. ./PDY

##################################
# Working directories
##################################
export DATA=${DATA:-${DATAROOT}/${job}}
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##################################
# Define COM directories
##################################
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/}
mkdir -p $COMOUT
export NWGES=${NWGES:-${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}}

##################################
# Execute the script.
${HOMEfv3}/scripts/fv3/exhiresw_archive.sh
export err=$?
##################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
