#!/bin/ksh
set -x

. $HOMEfv3/jobs/JREGIONAL_ENVIR
. $USHfv3/run_commands_forecast.sh

####################################
# SENDCOM - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export WGRIB2=${WGRIB2:-${EXECfv3}/wgrib2new}

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY and CDATE are passed in through Rocoto xml
#setpdy.sh
#. ./PDY

#####################################
# Working directories
#####################################
export INPUT_DATA_EVEN=${INPUT_DATA_EVEN:-${STMP}/tmpnwprd/regional_posteven_${dom}_${PDY}${cyc}}
export INPUT_DATA_ODD=${INPUT_DATA_ODD:-${STMP}/tmpnwprd/regional_postodd_${dom}_${PDY}${cyc}}
export DATA=${DATA:-${STMP}/tmpnwprd/${job}}
# if [ -d $DATA ]; then
#   rm -rf $DATA
# fi

if [ ! -e $DATA ]; then
mkdir -p $DATA
fi

cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

#####################################
# wcoss environment settings
#####################################
export OMP_NUM_THREADS=1

env

#####################################
# Execute the script.
${HOMEfv3}/scripts/exregional_prdgen.sh_odd
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
